import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/app/(auth)/admin-components/Sidebar";
import "./admins.css";
import "react-toastify/dist/ReactToastify.css";
import AdminHeader from "./admin-components/AdminHeader";
import { ToastContainer } from "react-toastify";
import { authToken } from "./common/tokens";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await authToken();

  return (
    <div className={`${geistSans.variable} ${geistMono.variable} flex`}>
      <div className="w-full font-family-karla flex">
        <Sidebar />
        <div className="flex-1 transition-all duration-300 ease-in-out lg:ml-[290px]">
          <AdminHeader token={token || ""} />

          <ToastContainer />
          <div className="w-full overflow-x-hidden flex flex-col">
            <main className="w-full flex-grow p-6">{children}</main>
          </div>
        </div>
      </div>
    </div>
  );
}
